org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
mod_id=byepregen
mod_name=ByePregen
mod_license=LGPL-3.0
mod_version=1.1.2.0
mod_group_id=com.moepus
mod_authors=MoePus
mod_description=
java_version=25

# Minecraft and mappings
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_form_version=26.1.2-1

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

# NeoForge
neoforge_version=26.1.2.97
neoforge_loader_version_range=[4,)

# Shared build dependencies
mixin_version=0.17.3+mixin.0.8.7
mixinextras_version=0.5.4
mixinlite_version=0.2.0

# Optional NeoForge Connector runtime (disabled by default)
connector_version=3.0.0-beta.6
launchpad_version=1.9.1+26.1.2
forgified_fabric_api_version=0.155.2+26.1.2+3.5.0

# Optional Modrinth dependencies
zfastnoise_fabric_version=shxfMPzi
zfastnoise_neoforge_version=7iYx7Gsk
terrablender_fabric_version=NIXt6lha
terrablender_neoforge_version=cWLGFrxw
c2me_fabric_version=riLBXg84
c2me_neoforge_version=bxj8Dzwh
voxy_fabric_version=Zt3LPI0b
lithium_fabric_version=Oqq8TOAV
lithium_neoforge_version=eZ0KJiEA
sodium_fabric_version=vf7UgZpC
sodium_neoforge_version=UETw0GTI
architectury_fabric_version=hNxqF6r7
architectury_neoforge_version=uNG0WqnM
chunky_fabric_version=4Eotm6ov
chunky_neoforge_version=EyCqftOK
scalablelux_fabric_version=ToW8oIIq
scalablelux_neoforge_version=XaTCC66i
