org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
mod_id=byepregen
mod_name=ByePregen
mod_license=LGPL-3.0
mod_version=1.1.2.5
mod_group_id=com.moepus
mod_authors=MoePus
mod_description=
java_version=25

# Minecraft and mappings
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_form_version=26.2-2

# Fabric
fabric_loader_version=0.19.5
fabric_api_version=0.160.0+26.2

# NeoForge
neoforge_version=26.2.0.87
neoforge_loader_version_range=[4,)

# Shared build dependencies
mixin_version=0.17.4+mixin.0.8.7
mixinextras_version=0.5.5
mixinlite_version=0.2.0

# Optional Modrinth dependencies
zfastnoise_fabric_version=9TGMeiu2
zfastnoise_neoforge_version=bL1UyVT2
terrablender_fabric_version=KQix25Qc
terrablender_neoforge_version=TzDe72Nr
c2me_fabric_version=jSMMstCy
c2me_neoforge_version=Gj7cXd5I
voxy_fabric_version=LzyXnE51
lithium_fabric_version=f7vZ0VWU
lithium_neoforge_version=J9CowDXK
sodium_fabric_version=xJZxADzI
sodium_neoforge_version=DmnNKsfS
architectury_fabric_version=Jmfixwxe
architectury_neoforge_version=t6H9g0ug
chunky_fabric_version=4Eotm6ov
chunky_neoforge_version=EyCqftOK
scalablelux_fabric_version=EKLUURiy
scalablelux_neoforge_version=sj4ujwsT
tectonic_fabric_version=tGbplDzo
tectonic_neoforge_version=c7tXsFY6
