modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "byepregen_surface_test"
version = "1"
displayName = "ByePregen Surface Runtime Test"
description = '''Test-only transformed-runtime probes for the Surface compiler.'''

[[dependencies."byepregen_surface_test"]]
modId = "byepregen"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies."byepregen_surface_test"]]
modId = "terrablender"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "SERVER"
