modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

["lithium:options"]
"mixin.world.chunk_access" = false

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "c2me"
type = "optional"
versionRange = "[0.4.0-alpha.0.116,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "noisiumed"
type = "incompatible"
reason = "Please use ZFastNoise instead"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "noisium"
type = "incompatible"
reason = "Please use ZFastNoise instead"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "antixray"
type = "incompatible"
reason = "ByePregen dont work with anti-xray mods"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "BOTH"
