package com.moepus.byepregen.mixin.surface;

import com.moepus.byepregen.MixinFeature;
import com.moepus.byepregen.MixinGate;
import net.minecraft.world.level.levelgen.material.MaterialRuleContext;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;
import org.spongepowered.asm.mixin.gen.Invoker;

/**
 * Unique getter names for the values the generated surface rules read.
 *
 * <p>26.2 read its context through these accessors. 26.3's {@code MaterialRuleContext} exposes public
 * getters, but the generated bytecode cannot call them: Minecraft's production namespaces rename
 * them, and the {@code ()I} getters cannot be found by shape either (several share that descriptor).
 * Compiling the accessor names into the generated class instead keeps it remap-proof, because mixin
 * members live in this mod's own namespace.</p>
 */
@MixinGate(feature = MixinFeature.SURFACE_RULE_COMPILER)
@Mixin(MaterialRuleContext.class)
public interface MaterialRuleContextAccessMixin {
    @Accessor("blockX")
    int byepregen$blockX();

    @Accessor("blockY")
    int byepregen$blockY();

    @Accessor("blockZ")
    int byepregen$blockZ();

    @Accessor("surfaceDepth")
    int byepregen$surfaceDepth();

    @Accessor("waterHeight")
    int byepregen$waterHeight();

    @Accessor("stoneDepthAbove")
    int byepregen$stoneDepthAbove();

    @Accessor("stoneDepthBelow")
    int byepregen$stoneDepthBelow();

    @Invoker("getSurfaceSecondary")
    double byepregen$getSurfaceSecondary();

    @Invoker("getMinSurfaceLevel")
    int byepregen$getMinSurfaceLevel();
}
